### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by kkwoff** [IIInitiationnn/BloodEmporium#12]
initialisation, merging
Traceback (most recent call last):
  File "state.py", line 120, in run
  File "mergedbase.py", line 55, in __init__
  File "mergedbase.py", line 80, in __get_valid_images
AttributeError: 'NoneType' object has no attribute 'shape'
is。why？

**Comment by IIInitiationnn** [comment]
Please check the solution to https://github.com/IIInitiationnn/BloodEmporium/issues/5

**Comment by kkwoff** [comment]
okey，thx bro im try and working
