### ISSUE TITLE
Failed to execute script 'main' due to unhandled exception : no such file or diretory

### ISSUE THREAD

**Issue by hsy991008** [IIInitiationnn/BloodEmporium#33]
Traceback (most recent call last):
File "utils\plots.py", line 58, in check_font
File "PIL\ImageFont.py", line 959, in truetype
File "PIL\ImageFont.py", line 956, in freetype
File "PIL\ImageFont.py", line 247, in __init__
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "urllib\request.py", line 1354, in do_open
File "http\client.py", line 1252, in request
File "http\client.py", line 1298, in _send_request
File "http\client.py", line 1247, in endheaders
File "http\client.py", line 1007, in _send_output
File "http\client.py", line 947, in send
File "http\client.py", line 1421, in connect
File "ssl.py", line 500, in wrap_socket
File "ssl.py", line 1040, in _create
File "ssl.py", line 1309, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main.py", line 29, in 
File " _bootstrap>", line 991, in _find_and_load
File " _bootstrap>", line 975, in _find_and_load_unlocked
File " _bootstrap>", line 671, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
File "state.py", line 14, in 
File " _bootstrap>", line 991, in _find_and_load
File " _bootstrap>", line 975, in _find_and_load_unlocked
File " _bootstrap>", line 671, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
File "edge_detection.py", line 13, in 
File " _bootstrap>", line 991, in _find_and_load
File " _bootstrap>", line 975, in _find_and_load_unlocked
File " _bootstrap>", line 671, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
File "models\common.py", line 26, in 
from utils. plots import Annotator, colors, save_one_box
File " _bootstrap>", line 991, in _find_and_load
File " _bootstrap>", line 975, in _find_and_load_unlocked
File " _bootstrap>", line 671, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
File "utils\plots.py", line 69, in 
File "utils\plots.py", line 71, in Annotator
File "utils\plots.py", line 62, in check_font
File "torch\hub.py", line 597, in download_url_to_file
u = urlopen(req)
File "urllib\request.py", line 222, in urlopen
File "urllib\request.py", line 531, in open
File "urllib\request.py", line 640, in http_response
File "urllib\request.py", line 563, in error
File "urllib\request.py", line 502, in _call_chain
File "urllib\request.py", line 755, in http_error_302
File "urllib\request.py", line 531, in open
File "urllib\request.py", line 640, in http_response
File "urllib\request.py", line 563, in error
File "urllib\request.py", line 502, in _call_chain
File "urllib\request.py", line 755, in http_error_302
File "urllib\request.py", line 525, in open
File "urllib\request.py", line 542, in _open
File "urllib\request.py", line 502, in _call_chain
File "urllib\request.py", line 1397, in https_open
File "urllib\request.py", line 1357, in do_open
urllib.error.URLError:

**Comment by IIInitiationnn** [comment]
Are you running the pre-compiled executable or are you executing the script using your own instance of Python? If the latter, please download the app from https://github.com/IIInitiationnn/BloodEmporium/releases/latest.

**Comment by hsy991008** [comment]
I did download Blood.Emporium.1.0.0.zip from Assets and Right click administrator execution

**Comment by hsy991008** [comment]
I also try other vision ,they  all shows the same problem

**Comment by hsy991008** [comment]
after running Blood.Emporium.exe about 10s 

There's a popover like this

**Comment by hsy991008** [comment]
I also use my friend pc to do so it shows same problem

**Comment by IIInitiationnn** [comment]
Would you be able to send the full error message? (maybe paste it into a `.txt` file and send it)

**Comment by hsy991008** [comment]
I don't know why I was able to use it when I just went to implement it, maybe I restart my pc... Thanks anyway
