### ISSUE TITLE
Not working on Chinese or non-English game environment

### ISSUE THREAD

**Issue by Sieuno** [IIInitiationnn/BloodEmporium#37]
Version: Release v1.1.0-alpha.3 from github release
Fully clean-installation (not override old version)
When start, the cursor teleport to top left, then nothing happen.

DEBUG LOG
-----------------------------
merging
using 0 custom icons and 1105 vanilla icons
using profile: cheapskate (ignores perks)
run mode: naive
capturing screen
yolov8: detect claimable nodes
None
Traceback (most recent call last):
  File "state.py", line 264, in run
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

**Comment by IIInitiationnn** [comment]
Can you check that your bloodpoints (in the top right of your screen) are not obstructed when the program starts?
If you are still getting this error please send me a fullscreen screenshot of your game with the bloodweb open, and I will try to reproduce the error on my end.

**Comment by Klaex** [comment]
I had something similar happen:

```capturing screen
yolov8: detect and match all nodes
588943
yolov5obb: detect and link all edges
creating networkx graph
NODES
    1  iconAddon_cleanRag_survivor                inaccessible       
    2  iconFavors_primroseBlossomSachet_survivor  inaccessible       
    3  iconItems_toolboxWornOut_survivor          inaccessible       
    4  iconItems_toolbox_anniversary2022_survivor inaccessible       
    5  iconAddon_butterflyTape_survivor           accessible         
    6  iconFavors_jarOfSaltyLips_survivor         inaccessible       
    7  iconAddon_scissors_survivor                accessible         
    8  iconAddon_wideLens_survivor                inaccessible       
    9  iconAddon_ropeYellow_survivor              accessible         
    10 iconFavors_primroseBlossomSachet_survivor  accessible         
    11                                            origin_auto_enabled
EDGES
    1  iconAddon_cleanRag_survivor               9  iconAddon_ropeYellow_survivor             
    1  iconAddon_cleanRag_survivor               4  iconItems_toolbox_anniversary2022_survivor
    2  iconFavors_primroseBlossomSachet_survivor 10 iconFavors_primroseBlossomSachet_survivor 
    2  iconFavors_primroseBlossomSachet_survivor 8  iconAddon_wideLens_survivor               
    3  iconItems_toolboxWornOut_survivor         5  iconAddon_butterflyTape_survivor          
    5  iconAddon_butterflyTape_survivor          11                                           
    6  iconFavors_jarOfSaltyLips_survivor        7  iconAddon_scissors_survivor               
    7  iconAddon_scissors_survivor               11                                           
    9  iconAddon_ropeYellow_survivor             11                                           
    10 iconFavors_primroseBlossomSachet_survivor 11                                           
optimiser
    initial nodes
        1  iconAddon_cleanRag_survivor                -2700050 inaccessible       
        2  iconFavors_primroseBlossomSachet_survivor  200000   inaccessible       
        3  iconItems_toolboxWornOut_survivor          0        inaccessible       
        4  iconItems_toolbox_anniversary2022_survivor -4800100 inaccessible       
        5  iconAddon_butterflyTape_survivor           0        accessible         
        6  iconFavors_jarOfSaltyLips_survivor         -400030  inaccessible       
        7  iconAddon_scissors_survivor                -200015  accessible         
        8  iconAddon_wideLens_survivor                300000   inaccessible       
        9  iconAddon_ropeYellow_survivor              -1450033 accessible         
        10 iconFavors_primroseBlossomSachet_survivor  200000   accessible         
        11                                            0        origin_auto_enabled
4 (iconItems_toolbox_anniversary2022_survivor)
updating bloodweb
yolov8: detect all nodes
586443
optimiser
    updated nodes
        1 iconAddon_cleanRag_survivor   -2700050 => 0 inaccessible => claimed
        9 iconAddon_ropeYellow_survivor -1450033 => 0 accessible   => claimed
6 (iconFavors_jarOfSaltyLips_survivor)
updating bloodweb
yolov8: detect all nodes
None
Traceback (most recent call last):
  File "state.py", line 648, in run
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

It works again for a few nodes when I start it again but end up getting the same error:

```merging
using 0 custom icons and 1107 vanilla icons
using profile: personal otz
run mode: aware_multi
speed: fast
Fusing layers... 
Model Summary: 213 layers, 2004058 parameters, 0 gradients, 4.9 GFLOPs
capturing screen
yolov8: detect and match all nodes
582443
yolov5obb: detect and link all edges
creating networkx graph
NODES
    1  iconFavors_primroseBlossomSachet_survivor inaccessible       
    2  iconItems_toolboxWornOut_survivor         inaccessible       
    3  iconFavors_jarOfSaltyLips_survivor        accessible         
    4  iconAddon_butterflyTape_survivor          accessible         
    5  iconAddon_scissors_survivor               accessible         
    6  iconAddon_wideLens_survivor               inaccessible       
    7  iconFavors_primroseBlossomSachet_survivor accessible         
    8                                            claimed            
    9                                            claimed            
    10                                           claimed            
    11                                           origin_auto_enabled
EDGES
    1 iconFavors_primroseBlossomSachet_survivor 7  iconFavors_primroseBlossomSachet_survivor
    1 iconFavors_primroseBlossomSachet_survivor 6  iconAddon_wideLens_survivor              
    2 iconItems_toolboxWornOut_survivor         4  iconAddon_butterflyTape_survivor         
    3 iconFavors_jarOfSaltyLips_survivor        5  iconAddon_scissors_survivor              
    4 iconAddon_butterflyTape_survivor          11                                          
    5 iconAddon_scissors_survivor               11                                          
    7 iconFavors_primroseBlossomSachet_survivor 11                                          
    8                                           10                                          
    8                                           11                                          
    9                                           10                                          
optimiser
    initial nodes
        1  iconFavors_primroseBlossomSachet_survivor 200000  inaccessible       
        2  iconItems_toolboxWornOut_survivor         0       inaccessible       
        3  iconFavors_jarOfSaltyLips_survivor        -400030 accessible         
        4  iconAddon_butterflyTape_survivor          0       accessible         
        5  iconAddon_scissors_survivor               0       accessible         
        6  iconAddon_wideLens_survivor               300000  inaccessible       
        7  iconFavors_primroseBlossomSachet_survivor 200000  accessible         
        8                                            0       claimed            
        9                                            0       claimed            
        10                                           0       claimed            
        11                                           0       origin_auto_enabled
3 (iconFavors_jarOfSaltyLips_survivor)
updating bloodweb
yolov8: detect all nodes
579944
optimiser
    updated nodes
        3 iconFavors_jarOfSaltyLips_survivor   -400030 accessible => inaccessible
        5 iconAddon_scissors_survivor          0       accessible => claimed     
4 (iconAddon_butterflyTape_survivor)
updating bloodweb
yolov8: detect all nodes
None
Traceback (most recent call last):
  File "state.py", line 648, in run
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by IIInitiationnn** [comment]
As a temporary workaround, try adjusting your UI scale in your game settings.

**Comment by Sieuno** [comment]
The bug can repeat on game client that setting other language, I guess.
I still can't using BloodEmporium on Simplified Chinese on latest version(While it can work on 0.3.X, that strange).
And it worked when I switch to English.

**Comment by IIInitiationnn** [comment]
Ah yep, unfortunately the model for detecting the number of bloodpoints is not trained on the Chinese font.

**Comment by Sieuno** [comment]
Maybe is the training cause model overfitting?

**Comment by IIInitiationnn** [comment]
Prior to user reports about this issue, I was unaware that using the Chinese language would change the font. As such, I have 0 training samples with this different font, so it makes sense that the model would not detect it.

**Comment by Sieuno** [comment]
That’s it. I used it and think the software is very useful. 
Is there anything I could know if there is a plan to support Chinese?
I would provide any help that I can.
Anyway, thank you and your project!

**Comment by IIInitiationnn** [comment]
Since there have been numerous issues with the bloodpoint-reading feature of the app, I am going to temporarily remove this feature for the next update so that users can use the app normally without disruption. I will continue refining the precision of the models and algorithms before I reincorporate the feature in the future.

**Comment by Sieuno** [comment]
Thanks for replying. I don’t think the issue will be resolved until the function in Chinese or other languages works properly. I will edit the title so that others who encounter the same problem can find the discussion easily.
