### ISSUE TITLE
Can't open: SSL Error

### ISSUE THREAD

**Issue by DoctorDinosaur** [IIInitiationnn/BloodEmporium#45]
Using release 1.2.1:

```Traceback (most recent call last):
  File "utils\plots.py", line 58, in check_font
  File "PIL\ImageFont.py", line 959, in truetype
  File "PIL\ImageFont.py", line 956, in freetype
  File "PIL\ImageFont.py", line 247, in __init__
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "state.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "edge_detection.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "models\common.py", line 26, in <module>
    from utils.plots import Annotator, colors, save_one_box
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "utils\plots.py", line 69, in <module>
  File "utils\plots.py", line 71, in Annotator
  File "utils\plots.py", line 62, in check_font
  File "torch\hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1397, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>
```
Upon opening

**Comment by IIInitiationnn** [comment]
May have a tentative fix for anyone who runs into this issue (seems to have popped up a couple times over the years now):
1. Go to `<Blood Emporium installation path>\yolov5_obb` and copy the `Arial.ttf` file (should be at `C:\Users\<your user>\AppData\Local\Programs\Blood Emporium\yolov5_obb` by default).
2. Go to `C:\Users\<your user>\AppData\Roaming\Ultralytics` and paste the `Arial.ttf` file into this folder.

**Comment by IIInitiationnn** [comment]
I have also seen that some people have been able to resolve this issue by going to their installation folder and moving the `Arial.ttf` file from the `yolov5_obb` subfolder into the main `Blood Emporium` folder.

**Comment by LukeJansen** [comment]
> I have also seen that some people have been able to resolve this issue by going to their installation folder and moving the `Arial.ttf` file from the `yolov5_obb` subfolder into the main `Blood Emporium` folder.

This fixed the issue for me! 👍

**Comment by IIInitiationnn** [comment]
I've updated the installer file on the latest version (v1.2.21) so hopefully this won't be an issue anymore.
