### ISSUE TITLE
How to compile / Linux build

### ISSUE THREAD

**Issue by ahmouse15** [IIInitiationnn/BloodEmporium#51]
Hello,

I tried manually compiling (well, bundling) the program since there is no Linux build available, but it seems that the repo doesn't actually include the `yolov5_obb` directory needed to build it, which I presume contains the actual ML models.

Would you be able to either provide a Linux build, or include the necessary files for others to build it themselves?

**Comment by ahmouse15** [comment]
P.S. After testing it on Linux through Wine, it starts up, continuously auto clicks, but the cursor sits up in the top left corner. I am using a custom icon pack and have set the path to it in settings, and I can confirm it's loaded since it shows the custom icons in the filtering list

**Comment by IIInitiationnn** [comment]
The `yolov5_obb` repo can be cloned from https://github.com/hukaixuan19970627/yolov5_obb though I am not sure if I modified anything.
For your follow-up comment, if you can send the relevant logs from the `logs` folder I may be able to find the source of the issue.

**Comment by Dylancyclone** [comment]
I am also on linux (running the precompiled build through Wine/Bottles), and when I try to run the app it will also throw the cursor up in the top left corner and not do anything else.

I would try compiling, but I don't have any experience with `pyinstaller` to bundle a linux build

Let me know if there's any other info that could help!

<details><summary>Full Log</summary>
<p>

```
initialising (v1.2.10)
merging
using 0 custom icons and 1261 vanilla icons
using profile: [BUNDLED] otz's tier list (prioritises perks) (bundled: True) for character survivor
run mode: aware_multi
speed: fast
Fusing layers... 
Model Summary: 213 layers, 2004058 parameters, 0 gradients, 4.9 GFLOPs
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...

``` 

</p>
</details>

**Comment by IIInitiationnn** [comment]
I'm not too familiar with the architecture of Wine, but from the log, it seems that the application is not detecting anything on your screen. If a virtual desktop is being used, Blood Emporium and Dead by Daylight would probably both need to be run from the same environment so that the app can see the game.

If we can't figure out a simple workaround, I'll need to set up an environment to test a Linux build. If there's any relevant information about the configuration and architecture of Wine that might help with figuring out a workaround, please let me know.

**Comment by Dylancyclone** [comment]
I tried running `python main.py` on linux without compiling with `pyinstaller` and ran into a couple issues. First I got the error:
```
Traceback (most recent call last):
  File "/var/mnt/d/Documents/Git/BloodEmporium/main.py", line 14, in <module>
    from frontend.dialogs import UpdateDialog, UpdatingDialog
  File "/var/mnt/d/Documents/Git/BloodEmporium/frontend/dialogs.py", line 5, in <module>
    from frontend.generic import Icons
  File "/var/mnt/d/Documents/Git/BloodEmporium/frontend/generic.py", line 9, in <module>
    from pynput import keyboard
  File "/run/host/var/mnt/d/Documents/Git/BloodEmporium/venv/lib/python3.10/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/run/host/var/mnt/d/Documents/Git/BloodEmporium/venv/lib/python3.10/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/run/host/var/mnt/d/Documents/Git/BloodEmporium/venv/lib/python3.10/site-packages/pynput/_util/__init__.py", line 77, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))
```

Which I bypassed with `sudo xhost +` (this command basically turns off all security surrounding which applications can access the screen. It can be turned off with `sudo xhost -`) (This could be the issue the regular application is running into)

Then I ran into:
```
connected to database
disconnected from database
Traceback (most recent call last):
  File "/var/mnt/d/Documents/Git/BloodEmporium/main.py", line 27, in <module>
    from backend.state import State
  File "/var/mnt/d/Documents/Git/BloodEmporium/backend/state.py", line 14, in <module>
    from backend.edge_detection import EdgeDetection
  File "/var/mnt/d/Documents/Git/BloodEmporium/backend/edge_detection.py", line 13, in <module>
    from yolov5_obb.models.common import DetectMultiBackend
  File "/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/models/common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/utils/datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/utils/augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/utils/general.py", line 35, in <module>
    from utils.nms_rotated import obb_nms
  File "/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/utils/nms_rotated/__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (/var/mnt/d/Documents/Git/BloodEmporium/yolov5_obb/utils/nms_rotated/__init__.py)
```
And got stuck.

So I instead looked at the wine route again, and ran the compiled binary from the command line to see if there was any extra information, and I saw this in the log:
```
connected to database
disconnected from database
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000000055C4C0D0>.
  warnings.warn(
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000000055C703A0>.
  warnings.warn(
connected to database
disconnected from database
Model summary (fused): 168 layers, 11129454 parameters, 0 gradients, 28.5 GFLOPs
initialising (v1.2.10)
merging
using 0 custom icons and 1261 vanilla icons
using profile: [BUNDLED] otz's tier list (prioritises perks) (bundled: True) for
 character survivor
run mode: aware_multi
speed: fast
Fusing layers...
Model Summary: 213 layers, 2004058 parameters, 0 gradients, 4.9 GFLOPs
capturing screen
yolov8: detect and match all nodes
Ultralytics YOLOv8.0.33  Python-3.8.10 torch-1.13.1+cpu CPU
nothing detected, trying again...
capturing screen
yolov8: detect and match all nodes
nothing detected, trying again...
```

Unfortunately I really don't know enough about wine to know if that's a wine issue or not.

As for configuration, I'm not really doing anything special with wine, I've left everything as default, and I've made sure any kind of virtual desktop setting is off. I've tried using [Bottles](https://usebottles.com/) to have an easily clean environment

Let me know if there's any other info that can help!

**Comment by F1nsi** [comment]
I dug into this a bit - I think there are actually two separate problems here, and only one of them is really a "build" issue.

1. The Wine case ("cursor jumps to top-left, nothing detected") is not a code bug it's screen-capture isolation.

In the log the pipeline is actually working: capturing screen → yolov8: detect and match all nodes → nothing detected. So the model loads and runs fine; the problem is that pyautogui.screenshot() (in backend/image.py) under Wine grabs the Wine prefix's own virtual screen, not the real desktop where Dead by Daylight is running. If DBD runs natively or through Proton in a different prefix, the Blood Emporium process literally cannot see the game window, so YOLO gets a blank/wrong image and detects nothing. The cursor ends up top-left because no origin node is ever matched.

This can't really be fixed in the app code - it's how Wine sandboxes the display. The only reliable workaround is to make sure Blood Emporium and DBD share the same display/environment that the screenshot API can capture (same prefix / same X display, no separate virtual desktop). Worth confirming by dumping what pyautogui.screenshot() actually returns under Wine - I'd bet it's a black frame or the Wine desktop, not the game.

2. The native python main.py case fails earlier, on a missing compiled extension.

The ImportError: cannot import name 'nms_rotated_ext' comes from backend/edge_detection.py importing yolov5_obb, whose rotated-NMS op is a C++/CUDA extension that has to be built - it isn't shipped precompiled for Linux. From the yolov5_obb repo:

cd yolov5_obb/utils/nms_rotated
python setup.py build_ext --inplace   # needs a matching torch + compiler (CUDA optional; CPU build works)

Until that extension is compiled, edge_detection.py can't be imported at all, so the app won't start regardless of the display issue. (The pynput X-connection error before that is just the missing display auth — xhost + / a proper DISPLAY works around it, as noted.)

So for a real Linux build you'd need: compile nms_rotated_ext against the Linux torch, run under a real X display, and a separate Linux PyInstaller spec (the current .spec files are Windows-oriented). Happy to help test a Linux spec, but the Wine "nothing detected" part is an environment problem, not something a Linux build alone will fix.

**Comment by ahmouse15** [comment]
@F1nsi What in the AI slop did I just read?

**Comment by F1nsi** [comment]
I tried to find a solution to the problem myself but couldn't, so I decided to ask Opus; figuring he was right, I simply sent you this message.
