### ISSUE TITLE
unhandled exception in script

### ISSUE THREAD

**Issue by H1W0XXX** [IIInitiationnn/BloodEmporium#53]
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    from backend.state import State
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "state.py", line 14, in <module>
    from backend.edge_detection import EdgeDetection
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "edge_detection.py", line 13, in <module>
    from yolov5_obb.models.common import DetectMultiBackend
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "models\common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "utils\datasets.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "utils\augmentations.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "utils\general.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "utils\metrics.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "matplotlib\__init__.py", line 991, in <module>
  File "matplotlib\__init__.py", line 639, in matplotlib_fname
  File "matplotlib\__init__.py", line 636, in gen_candidates
  File "matplotlib\__init__.py", line 335, in wrapper
  File "matplotlib\__init__.py", line 582, in get_configdir
  File "matplotlib\__init__.py", line 537, in _get_config_or_cache_dir
  File "pathlib.py", line 1181, in resolve
  File "pathlib.py", line 206, in resolve
OSError: [WinError 1] 函数不正确。: 'Z:\\TEMP\\tmp0lv3knao'

Beacuse I set windows temp dir to Z.Change it to default working good.

**Comment by IIInitiationnn** [comment]
Sorry, I'm not quite following what the problem is. Would you be able to elaborate on what steps you took, and what issues you are running into?

**Comment by H1W0XXX** [comment]
After I changed the path of the temporary folder in the Windows system to Z:/temp, this error occurred. However, when I reverted it to the default settings, the error disappeared.
