### ISSUE TITLE
Can you help me with this error?

### ISSUE THREAD

**Issue by kryptokall** [IIInitiationnn/BloodEmporium#54]
Guys, I'm facing an error whenever I click the 'Run' button inside the application. I don't know if this has anything to do with the fact that my game's "Icons" folder isn't in the default path, but I've already indicated the correct path in the settings and the error is still happening. 

I'll leave the log below so you can see what's going on:

```
initialising (v1.2.9)
merging
using 0 custom icons and 1261 vanilla icons
using profile: cheapskate (prioritize perks)
Traceback (most recent call last):
  File "state.py", line 227, in run
  File "mergedbase.py", line 31, in __init__
  File "mergedbase.py", line 72, in __get_valid_images
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```
Thanks in advance!

**Comment by IIInitiationnn** [comment]
Previous instances of this error have typically arisen from special unicode characters in the installation path. Please relocate the folder where Blood Emporium was installed if this is the case. Let me know if this does not resolve your issue.
