### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by gregm8** [IIInitiationnn/BloodEmporium#58]
I get this error when trying to start the application. I have not used it for a while and have no clue what could have caused this, or what could possibly be the soluion.
I have installed the latest upddate, but the error remains.
If the solution is to uninstall/reinstall, I would like to keep the changes I made, but I'm not sure where the save is located.

error is as follows...

"
Failed to execute script 'main' due to unhandled exception: Expecting value: line 7571 column 25 (char 229810)

Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "frontend\pages\bloodweb.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "data.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "paths.py", line 6, in <module>
  File "paths.py", line 13, in Path
  File "config.py", line 40, in __init__
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 7571 column 25 (char 229810)
"

**Comment by gregm8** [comment]
<frozen importlib._bootstrap>
was left out of Copy&Paste. everywhere there is "" had <frozen importlib._bootstrap> inside.

**Comment by gregm8** [comment]
frozen importlib._bootstrap
was removed when posting the message, every where there is "" was frozen importlib._bootstrap

**Comment by IIInitiationnn** [comment]
It appears your configuration file is corrupted. If you can navigate to the app's install location, there should be a file called `config.json`. If you do not have any old profiles you want to preserve, you can just delete this file and relaunch the app. If you want to salvage whatever remains from the corrupted file, you can either fix it yourself if you are familiar with the JSON file format, or upload it here, and I will have a look at it for you instead.

**Comment by gregm8** [comment]
[config.json](https://github.com/user-attachments/files/18140295/config.json)

I appreciate that you've considered helping. I only want to salvage it because I spent time getting survivor exactly how I want it.

Because I don't know what's involved, I'll leave it up to you if it's worth your time. I only had the survivor, and one or two killers in the order I wanted, so it's not as bad as it could be if I have to re-do, thankfully.

**Comment by IIInitiationnn** [comment]
If you had a custom profile, unfortunately it has been corrupted and you'll have to remake the profile. However, if the changes you made were to one of the cheapskate profiles then I can repair it and send it back.
I would also advise exporting your profiles as `.emp` files as a form of backup in case this happens again, at which point you can simply reimport the profile.

**Comment by gregm8** [comment]
I only ever used the otz one that prioritsed the perks.

**Comment by IIInitiationnn** [comment]
Unfortunately you will need to recreate your profile. I will be marking this as resolved for now, please feel free to reopen this thread if you are still having issues.
